import { type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { MadeGeneratedModule, MadeGeneratedSharedModule } from './generated/module.js';
import { MadeValidator, registerValidationChecks } from './made-validator.js';
import { CustomScopeComputation } from './made-scope.js';
/**
 * Declaration of custom services - add your own service classes here.
 */
export type MadeAddedServices = {
    validation: {
        MadeValidator: MadeValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type MadeServices = LangiumServices & MadeAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const MadeModule: Module<MadeServices, PartialLangiumServices & MadeAddedServices> = {
    references:{
        ScopeComputation: (services) => new CustomScopeComputation(services)
    },
    validation: {
        MadeValidator: () => new MadeValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createMadeServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Made: MadeServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        MadeGeneratedSharedModule
    );
    const Made = inject(
        createDefaultModule({ shared }),
        MadeGeneratedModule,
        MadeModule
    );
    shared.ServiceRegistry.register(Made);
    registerValidationChecks(Made);
    return { shared, Made };
}
