name: Publish VS Code Extension

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish Extension
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install VSCE (VS Code Extension Manager)
      - name: Install VSCE
        run: npm install -g @vscode/vsce

      # Install dependencies
      - name: Install Dependencies
        run: npm ci

      - name: Generate Langium Files
        run: npm run langium:generate

      # Package and publish the extension
      - name: Publish Extension
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: |
          vsce package
          vsce publish
